import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Gift, Heart, Sparkles } from "lucide-react";
import { InquiryForm } from "@/components/inquiry-form";

export const metadata: Metadata = { title: "Coffrets & cadeaux sur mesure", description: "Coffrets vin, accords gourmands et alternatives sans alcool à offrir aux proches, collaborateurs ou équipes." };

export default function CoffretsPage() {
  return <main>
    <section className="editorial-hero gift-hero"><div className="editorial-hero-copy"><span className="eyebrow">GUEULES DE VIGNERONS / LES BELLES ATTENTIONS</span><h1>Offrir du vin, <em>c&apos;est offrir une histoire.</em></h1><p>Un cadeau qui se débouche, se savoure et se raconte. Nous composons des coffrets pensés pour la personne qui les recevra, pas pour remplir une case.</p><Link href="#composer" className="button button-dark">Imaginer mon coffret <ArrowUpRight size={18} /></Link></div><div className="editorial-hero-image"><Image src="/images/gift-boxes.jpg" alt="Un coffret cadeau contenant deux bouteilles et des gourmandises" fill priority sizes="(max-width: 800px) 100vw, 50vw" className="cover-image" /><span>UNE ATTENTION À PARTAGER, PAS À RANGER.</span></div></section>
    <section className="gift-intro page-shell"><span className="eyebrow">01 / LES POSSIBILITÉS</span><h2>À chaque personne, <em>la bonne attention.</em></h2><div className="gift-options"><article><Gift size={30} strokeWidth={1.1} /><span>01 / LE DUO</span><h3>Deux bouteilles,<br />mille façons de dire merci.</h3><p>Un duo choisi avec soin : complémentaire, surprenant ou totalement à l&apos;image de la personne à qui vous l&apos;offrez.</p></article><article><Heart size={30} strokeWidth={1.1} /><span>02 / L&apos;ACCORD</span><h3>Le plaisir va<br />bien avec le plaisir.</h3><p>Deux flacons, une sélection gourmande, des accords mets-vins : le coffret qui ouvre l&apos;appétit et la conversation.</p></article><article><Sparkles size={30} strokeWidth={1.1} /><span>03 / SANS ALCOOL</span><h3>Tout le monde<br />a sa place à table.</h3><p>Jus de fruits de caractère et alternatives sans alcool pour célébrer avec la même attention, autrement.</p></article></div></section>
    <section className="gift-business"><div className="gift-business-image"><Image src="/images/gift-boxes.jpg" alt="Coffrets de bouteilles prêts à offrir" fill sizes="(max-width: 800px) 100vw, 50vw" className="cover-image" /></div><div className="gift-business-copy"><span className="eyebrow eyebrow-light">POUR VOS ÉQUIPES & CLIENTS</span><h2>Des cadeaux d&apos;entreprise <em>qui créent du lien.</em></h2><p>Pour un CSE, une équipe, des clients ou un événement : nous adaptons les coffrets à votre budget, vos quantités et votre message. Avec ou sans alcool, toujours avec intention.</p><Link href="/professionnels" className="text-link text-link-light">Découvrir notre approche pro <ArrowRight size={18} /></Link></div></section>
    <section id="composer" className="form-section page-shell"><div className="form-intro"><span className="eyebrow">02 / FAISONS-LE ENSEMBLE</span><h2>À qui allez-vous <em>faire plaisir ?</em></h2><p>Dites-nous pour qui, pour quelle occasion et à quel budget. Nous imaginerons une proposition qui a du sens.</p><div className="form-side-note">✳ Vous préférez parler d&apos;une dégustation ? <Link href="/club-epicure">Découvrez le Club Épicure <ArrowUpRight size={14} /></Link></div></div><InquiryForm type="cadeau" showOrganization buttonLabel="Imaginer mon coffret" message="Bonjour, j'aimerais créer un coffret pour ... personnes. Mon budget et mon occasion : ..." /></section>
  </main>;
}
