import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Building2, Gift, UtensilsCrossed } from "lucide-react";
import { InquiryForm } from "@/components/inquiry-form";

export const metadata: Metadata = { title: "Professionnels — restaurants & entreprises", description: "Carte des vins, accompagnement de restaurant, dégustations privées, formation et coffrets d'entreprise avec Gueules de Vignerons par RVins." };

export default function ProfessionnelsPage() {
  return <main>
    <section className="editorial-hero pro-hero"><div className="editorial-hero-copy"><span className="eyebrow">GUEULES DE VIGNERONS / À VOS CÔTÉS</span><h1>Le bon vin, <em>c&apos;est aussi une belle collaboration.</em></h1><p>Vous avez une table, une équipe, une idée à célébrer ? Nous apportons le vin, le regard et le sens du détail. Le reste, nous l&apos;imaginons ensemble.</p><div className="hero-actions"><Link href="#offres-pro" className="button button-dark">Découvrir nos offres <ArrowRight size={18} /></Link><Link href="/espace-pro" className="text-link">Mon espace pro <ArrowUpRight size={18} /></Link></div></div><div className="editorial-hero-image"><Image src="/images/pro-service.jpg" alt="Un sommelier sert un verre de vin dans un restaurant" fill priority sizes="(max-width: 800px) 100vw, 50vw" className="cover-image" /><span>UNE RELATION QUI SE CULTIVE, VERRE APRÈS VERRE.</span></div></section>
    <section className="pro-intro page-shell"><span className="eyebrow">01 / NOTRE APPROCHE</span><h2>Un partenaire de vin.<br /><em>Un partenaire tout court.</em></h2><p>Pas de catalogue posé sur un comptoir et puis plus rien. Nous aimons comprendre votre lieu, votre clientèle et vos envies pour construire une sélection qui vous ressemble, et vous accompagner dans le temps.</p></section>
    <section id="offres-pro" className="pro-offers"><div className="page-shell"><div className="section-heading-row"><div><span className="eyebrow">02 / TROIS FAÇONS D&apos;AVANCER ENSEMBLE</span><h2>Une réponse à <em>chaque projet.</em></h2></div></div><div className="pro-offer-grid"><article><span className="offer-icon"><UtensilsCrossed size={27} strokeWidth={1.2} /></span><span className="offer-number">01 / RESTAURATEURS</span><h3>Une carte qui raconte votre table.</h3><p>Sélection locale et sur mesure, construction de la carte des vins, conseils d&apos;accords, suivi des références et accompagnement du service.</p><ul><li>Carte des vins pensée pour votre cuisine</li><li>Suivi et renouvellement des cuvées</li><li>Conseil & formation de l&apos;équipe</li></ul><Link href="/contact?objet=pro" className="text-link">Parlons de votre carte <ArrowRight size={17} /></Link></article><article><span className="offer-icon"><Building2 size={27} strokeWidth={1.2} /></span><span className="offer-number">02 / ENTREPRISES</span><h3>Des moments dont on se souvient.</h3><p>Dégustations privées, ateliers d&apos;équipe et formations accessibles : des expériences qui font se rencontrer les personnes autant que les vins.</p><ul><li>Dégustations privées & séminaires</li><li>Ateliers de découverte du vin</li><li>Expériences avec accords gourmands</li></ul><Link href="/club-epicure" className="text-link">Explorer le Club Épicure <ArrowRight size={17} /></Link></article><article><span className="offer-icon"><Gift size={27} strokeWidth={1.2} /></span><span className="offer-number">03 / CSE & CADEAUX</span><h3>Une attention qui a du sens.</h3><p>Deux bouteilles, un accord gourmand, une version sans alcool : nous composons des coffrets adaptés à votre budget et à ceux qui les recevront.</p><ul><li>Coffrets sur mesure & en volume</li><li>Accords mets-vins et gourmandises</li><li>Alternatives sans alcool</li></ul><Link href="/coffrets" className="text-link">Imaginer mes coffrets <ArrowRight size={17} /></Link></article></div></div></section>
    <section className="pro-account-banner"><div className="page-shell"><div><span className="eyebrow eyebrow-light">UN ESPACE RIEN QU&apos;À VOUS</span><h2>Vos projets vin, <em>au même endroit.</em></h2><p>Créez votre accès professionnel pour retrouver votre espace et nous transmettre vos besoins en quelques instants.</p></div><Link href="/espace-pro" className="button button-cream">Accéder à l&apos;espace pro <ArrowUpRight size={18} /></Link></div></section>
    <section className="form-section page-shell"><div className="form-intro"><span className="eyebrow">03 / FAISONS CONNAISSANCE</span><h2>Racontez-nous <em>votre projet.</em></h2><p>Une carte à construire, une dégustation à organiser ou une idée qui n&apos;entre dans aucune case ? Parlons-en simplement.</p></div><InquiryForm type="pro" showOrganization buttonLabel="Parlons de mon projet" /></section>
  </main>;
}
