import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";

export const metadata: Metadata = { title: "La maison — notre esprit", description: "La vision de Gueules de Vignerons par RVins : les personnes, les sensations et les histoires derrière chaque bouteille." };

export default function MaisonPage() {
  return <main>
    <section className="editorial-hero maison-hero"><div className="editorial-hero-copy"><span className="eyebrow">LA MAISON / NOTRE REGARD</span><h1>Le vin a une histoire. <em>Les gens aussi.</em></h1><p>Ici, nous aimons ce qui se passe autour de la bouteille autant que ce qu&apos;il y a dedans.</p><Link href="#notre-esprit" className="text-link">Découvrir notre esprit <ArrowRight size={18} /></Link></div><div className="editorial-hero-image"><Image src="/images/story-vineyard.jpg" alt="Des mains présentent des raisins au cœur d'un vignoble" fill priority sizes="(max-width: 800px) 100vw, 50vw" className="cover-image" /><span>LES MAINS AVANT LES MOTS. LES GENS AVANT LES ÉTIQUETTES.</span></div></section>
    <section id="notre-esprit" className="manifesto-section page-shell"><span className="eyebrow">01 / CE QUI NOUS ANIME</span><h2>Entre la précision du geste et <em>l&apos;émotion du moment.</em></h2><p>Il y a la technique, le terroir, le savoir-faire. Et puis il y a ce que l&apos;on ressent : un parfum inattendu, un souvenir qui revient, une table qui s&apos;anime. C&apos;est à cet endroit-là que nous avons envie de nous trouver.</p><div className="manifesto-columns"><div><span>01 / RENCONTRER</span><h3>Des visages, pas des fiches.</h3><p>Prendre le temps de comprendre qui fait le vin, et pourquoi il le fait.</p></div><div><span>02 / RESSENTIR</span><h3>Le plaisir avant le jargon.</h3><p>Mettre des mots simples sur ce que le vin nous fait vivre, sans jamais intimider.</p></div><div><span>03 / PARTAGER</span><h3>Une bouteille est un début.</h3><p>Créer des occasions de se retrouver, de transmettre et de faire découvrir.</p></div></div></section>
    <section className="faces-section"><div className="page-shell"><div className="section-heading-row"><div><span className="eyebrow">02 / LES VISAGES DE LA MAISON</span><h2>Les belles <em>gueules du vin.</em></h2><p>Parce que l&apos;histoire ne s&apos;arrête pas à celui qui produit, ni à celui qui sert.</p></div></div><div className="faces-grid"><div className="face-card"><div className="face-image"><Image src="/images/story-vineyard.jpg" alt="Mains de vendangeur tenant des raisins" fill sizes="(max-width: 650px) 100vw, 50vw" className="cover-image" /></div><div><span className="eyebrow">LES GUEULES DE VIGNERONS</span><h3>Celles et ceux qui font.</h3><p>Des gestes, des choix, des convictions : bientôt, les histoires des vignerons qui feront vivre cette maison.</p></div></div><div className="face-card"><div className="face-image"><Image src="/images/hero-dinner.jpg" alt="Amis partageant un verre autour d'une table" fill sizes="(max-width: 650px) 100vw, 50vw" className="cover-image" /></div><div><span className="eyebrow">LES GUEULES DE CLIENTS</span><h3>Celles et ceux qui partagent.</h3><p>Une rencontre, un souvenir, un vin préféré : parce que vous faites aussi partie de l&apos;histoire.</p></div></div></div></div></section>
    <section className="hall-section page-shell"><div><span className="eyebrow">03 / LE CARNET DES RENCONTRES</span><h2>Les domaines qui feront <em>la maison.</em></h2><p>Un espace pour mettre à l&apos;honneur les vignerons et domaines partenaires, au fil des rencontres. Aucun nom n&apos;est affiché sans leur accord : ici, chaque histoire se raconte pour de vrai.</p><Link href="/contact" className="text-link">Faire connaissance <ArrowRight size={18} /></Link></div><div className="hall-graphic"><span>LOIRE</span><span>BOURGOGNE</span><span>RHÔNE</span><span>ET TANT D&apos;AUTRES...</span><b>✳</b></div></section>
    <section className="simple-cta"><div className="page-shell"><span className="eyebrow eyebrow-light">L&apos;HISTOIRE CONTINUE</span><h2>Et si la prochaine rencontre <em>c&apos;était nous ?</em></h2><Link href="/contact" className="button button-cream">Parlons de vin <ArrowUpRight size={18} /></Link></div></section>
  </main>;
}
