import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, Sparkles } from "lucide-react";
import { InquiryForm } from "@/components/inquiry-form";

export const metadata: Metadata = { title: "Le Club Épicure — dégustations & expériences", description: "Trois façons de vivre la dégustation avec Gueules de Vignerons par RVins : Les Découvreurs, Les Explorateurs et Les Initiés." };

const levels = [
  { number: "01", name: "Les Découvreurs", subtitle: "Le premier pas, le plaisir déjà là.", budget: "L'INITIATION ACCESSIBLE", spirit: "Pour faire ses premiers pas dans l'univers du vin sans se tromper. Des cuvées accessibles mais riches en histoires, et des mots simples à poser sur les sensations.", audience: "Les curieux, les équipes en séminaire et les amis qui veulent partager un moment convivial et instructif.", note: "S'ouvrir à la découverte" },
  { number: "02", name: "Les Explorateurs", subtitle: "Sortir des sentiers battus.", budget: "LE BUDGET PLAISIR", spirit: "Pour celles et ceux qui ont déjà leurs repères et aiment être surpris. Domaines confidentiels, vieux millésimes ou accords mets-vins audacieux : la curiosité a du goût.", audience: "Les amateurs éclairés et les entreprises qui souhaitent laisser une vraie signature gustative.", note: "Oser l'inattendu" },
  { number: "03", name: "Les Initiés", subtitle: "Les émotions rares se partagent.", budget: "L'EXCEPTION À VIVRE", spirit: "Le rendez-vous des grands flacons. Des cuvées singulières, des icônes du vignoble et toute la beauté de la technicité, au service de l'émotion.", audience: "Les passionnés exigeants, les célébrations prestigieuses et les dîners d'affaires exclusifs.", note: "Vivre un moment d'exception" },
];

export default function ClubPage() {
  return <main>
    <section className="club-hero"><Image src="/images/club-table.jpg" alt="Verres de vin et bougies dressés pour une dégustation" fill priority sizes="100vw" className="cover-image" /><div className="club-hero-overlay" /><div className="page-shell club-hero-content"><span className="eyebrow eyebrow-light">GUEULES DE VIGNERONS / LE CLUB ÉPICURE</span><h1>Le vin est plus beau <em>quand on le vit ensemble.</em></h1><p>Des dégustations qui ressemblent à ceux qui les partagent. Curieux d&apos;un soir ou passionné de toujours : il y a une place pour vous à notre table.</p><Link href="#niveaux" className="button button-cream">Trouver mon expérience <ArrowDown size={18} /></Link></div><span className="club-hero-side">LA CURIOSITÉ SE PARTAGE ✳</span></section>
    <section className="club-intro page-shell"><span className="eyebrow">01 / L&apos;ESPRIT DU CLUB</span><h2>Pas simplement goûter.<br /><em>Se laisser surprendre.</em></h2><p>Une expérience autour du vin n&apos;a pas besoin d&apos;être intimidante pour être mémorable. Nous pensons chaque dégustation comme une rencontre entre des personnes, des histoires, des saveurs et le plaisir d&apos;être là.</p></section>
    <section id="niveaux" className="club-level-section"><div className="page-shell"><div className="section-heading-row"><div><span className="eyebrow">02 / CHOISISSEZ VOTRE VOYAGE</span><h2>Trois façons de <em>faire pétiller la curiosité.</em></h2></div></div><div className="level-grid">{levels.map((level) => <article className="level-card" key={level.number}><div className="level-top"><span>{level.number} / 03</span><Sparkles size={22} strokeWidth={1} /></div><span className="level-budget">{level.budget}</span><h3>{level.name}</h3><p className="level-subtitle">{level.subtitle}</p><div className="level-divider" /><div className="level-description"><b>L&apos;esprit</b><p>{level.spirit}</p><b>Pour qui ?</b><p>{level.audience}</p></div><Link href={`/contact?objet=club&niveau=${encodeURIComponent(level.name)}`} className="level-link">{level.note} <ArrowUpRight size={18} /></Link></article>)}</div><p className="level-footnote">Chaque expérience est imaginée sur mesure. Le format et le budget sont définis ensemble selon votre groupe et vos envies.</p></div></section>
    <section className="club-moment"><div className="club-moment-image"><Image src="/images/hero-dinner.jpg" alt="Des amis trinquent autour d'une table" fill sizes="(max-width: 800px) 100vw, 50vw" className="cover-image" /></div><div className="club-moment-copy"><span className="eyebrow">03 / À VOTRE IMAGE</span><h2>Votre moment,<br /><em>notre attention.</em></h2><p>Chez vous, en entreprise ou autour d&apos;une grande table : nous imaginons le bon format, les bons vins et, si vous le souhaitez, des accords gourmands avec un traiteur.</p><div className="club-steps"><span>ON ÉCHANGE <ArrowRight size={15} /></span><span>ON IMAGINE <ArrowRight size={15} /></span><span>ON PARTAGE <Sparkles size={15} /></span></div><Link href="#club-contact" className="text-link">Imaginer ma dégustation <ArrowRight size={18} /></Link></div></section>
    <section id="club-contact" className="form-section page-shell"><div className="form-intro"><span className="eyebrow">À VOUS DE JOUER</span><h2>On se retrouve <em>autour d&apos;un verre ?</em></h2><p>Racontez-nous l&apos;occasion, le nombre de personnes et ce qui vous ferait plaisir. Nous reviendrons vers vous pour imaginer la suite.</p></div><InquiryForm type="club" buttonLabel="Imaginer ma dégustation" showOrganization message="Bonjour, j'aimerais organiser une dégustation Club Épicure pour ... personnes. Mon occasion : ..." /></section>
  </main>;
}
